### Directions
    - The data required for this task has been provided in the file 'data.csv'
    - Read the questions provided for each cell and assign your answers to respective variables provided in the following cell.
    - If answers are floating point numbers round of updo two floating point after the decimal
      - for example 10.546 should be read as 10.55, 10.544 as 10.54 and 10.1 as 10.10
    - pandas and numpy packages are preinstalled for this task which should be sufficient to complete this task.
    - If you need any other additional package run !pip3 install <package_name> --user in a new cell.
    - You can either try out the solution in the same notebook or free to create additional notebook, but make sure you come back to this notebook to answer the questions.
    - Please dont change variable name meant to assign your answers.
    - You can create a new notebook to write your scripts for EDA and use this notebook to assign the answers.

In [1]:
import pandas as pd
import numpy as np

In [2]:
### Read the data (this will not be graded)
df=pd.read_csv("data.csv")
df.head()

,Day,Average temperature (°F),Average humidity (%),Average dewpoint (°F),Average barometer (in),Average windspeed (mph),Average gustspeed (mph),Average direction (°deg),Rainfall for month (in),Rainfall for year (in),Maximum rain per minute,Maximum temperature (°F),Minimum temperature (°F),Maximum humidity (%),Minimum humidity (%),Maximum pressure,Minimum pressure,Maximum windspeed (mph),Maximum gust speed (mph),Maximum heat index (°F)
0,1/01/2009,37.8,35,12.7,29.7,26.4,36.8,274,0.0,0.0,0.0,40.1,34.5,44,27,29.762,29.596,41.4,59.0,40.1
1,2/01/2009,43.2,32,14.7,29.5,12.8,18.0,240,0.0,0.0,0.0,52.8,37.5,43,16,29.669,29.268,35.7,51.0,52.8
2,3/01/2009,25.7,60,12.7,29.7,8.3,12.2,290,0.0,0.0,0.0,41.2,6.7,89,35,30.232,29.260,25.3,38.0,41.2
3,4/01/2009,9.3,67,0.1,30.4,2.9,4.5,47,0.0,0.0,0.0,19.4,-0.0,79,35,30.566,30.227,12.7,20.0,32.0
4,5/01/2009,23.5,30,-5.3,29.9,16.7,23.1,265,0.0,0.0,0.0,30.3,15.1,56,13,30.233,29.568,38.0,53.0,32.0

In [3]:
df.loc[4,'Day']

'5/01/2009'

In [4]:
df.shape

(3280, 20)

### What is the standard deviation of maximum windspeed across all the days

In [5]:
ws_std = np.std(df['Maximum windspeed (mph)'])
print(round(ws_std,2))

13.06



### What is the difference between 50th percentile and 75th percentile of average temperature

In [6]:
seventyfive=np.percentile(df['Average temperature (°F)'],75)
fifty=np.percentile(df['Average temperature (°F)'],50)
p_range =(seventyfive-fifty)
print(round(p_range,2))

12.2

### What is the pearson correlation between average dew point and average temperature

In [7]:
corr = np.corrcoef(df['Average dewpoint (°F)'],df['Average temperature (°F)'])
print(round(corr[0,1],2))

0.76



### Out of all the available records which month has the lowest average humidity.
    - Assign your answer as month index, for example if its July index is 7

In [8]:
df['Date'] = pd.to_datetime(df['Day'],format = '%d/%m/%Y')

In [9]:
df['month_index'] = df['Date'].dt.month
df.head(2)

,Day,Average temperature (°F),Average humidity (%),Average dewpoint (°F),Average barometer (in),Average windspeed (mph),Average gustspeed (mph),Average direction (°deg),Rainfall for month (in),Rainfall for year (in),...,Minimum temperature (°F),Maximum humidity (%),Minimum humidity (%),Maximum pressure,Minimum pressure,Maximum windspeed (mph),Maximum gust speed (mph),Maximum heat index (°F),Date,month_index
0,1/01/2009,37.8,35,12.7,29.7,26.4,36.8,274,0.0,0.0,...,34.5,44,27,29.762,29.596,41.4,59.0,40.1,2009-01-01,1
1,2/01/2009,43.2,32,14.7,29.5,12.8,18.0,240,0.0,0.0,...,37.5,43,16,29.669,29.268,35.7,51.0,52.8,2009-01-02,1

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3280 entries, 0 to 3279
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Day                       3280 non-null   object
 1   Average temperature (°F)  3280 non-null   float64
 2   Average humidity (%)      3280 non-null   int64
 3   Average dewpoint (°F)     3280 non-null   float64
 4   Average barometer (in)    3280 non-null   float64
 5   Average windspeed (mph)   3280 non-null   float64
 6   Average gustspeed (mph)   3280 non-null   float64
 7   Average direction (°deg)  3280 non-null   int64
 8   Rainfall for month (in)   3280 non-null   float64
 9   Rainfall for year (in)    3280 non-null   float64
 10  Maximum rain per minute   3280 non-null   float64
 11  Maximum temperature (°F)  3280 non-null   float64
 12  Minimum temperature (°F)  3280 non-null   float64
 13  Maximum humidity (%)      3280 non-null   int64
 14  Minimum humidity (%)      3280 non-null   int64
 15  Maximum pressure          3280 non-null   float64
 16  Minimum pressure          3280 non-null   float64
 17  Maximum windspeed (mph)   3280 non-null   float64
 18  Maximum gust speed (mph)  3280 non-null   float64
 19  Maximum heat index (°F)   3280 non-null   float64
 20  Date                      3280 non-null   datetime64[ns]
 21  month_index               3280 non-null   int64
dtypes: datetime64[ns](1), float64(15), int64(5), object(1)
memory usage: 563.9+ KB

In [11]:
np.argmin(df['Average humidity (%)'])

1300

In [12]:
dew_month =df.iloc[1300,21]
dew_month

1

### Which month has the highest median for maximum_gust_speed out of all the available records. Also find the repective value
    - hint: group by month

In [13]:
df_month_group_med = df.groupby(['month_index']).median()
df_month_group_med

,Average temperature (°F),Average humidity (%),Average dewpoint (°F),Average barometer (in),Average windspeed (mph),Average gustspeed (mph),Average direction (°deg),Rainfall for month (in),Rainfall for year (in),Maximum rain per minute,Maximum temperature (°F),Minimum temperature (°F),Maximum humidity (%),Minimum humidity (%),Maximum pressure,Minimum pressure,Maximum windspeed (mph),Maximum gust speed (mph),Maximum heat index (°F)
month_index,,,,,,,,,,,,,,,,,,,
1,30.40,43.0,9.00,30.1,7.5,10.90,254.0,0.030,0.03,0.0,41.50,20.50,68.0,24.0,30.2460,29.8875,21.9,32.2,41.50
2,29.65,45.0,8.40,30.0,7.6,11.20,260.0,0.075,0.27,0.0,40.40,19.40,76.5,26.0,30.1820,29.8155,23.0,34.5,40.40
3,37.60,42.0,13.60,29.9,6.5,9.80,246.0,0.080,0.60,0.0,50.10,25.00,77.0,20.0,30.1120,29.7360,21.9,31.1,50.10
4,40.70,49.0,21.50,29.9,5.1,7.90,251.0,0.320,1.32,0.0,54.40,27.50,84.0,22.0,30.0660,29.6900,19.6,27.6,54.40
5,48.90,55.0,30.40,29.8,3.9,6.20,258.0,1.060,3.04,0.0,61.20,34.90,87.0,24.0,29.9320,29.6510,17.3,26.0,61.20
6,60.40,45.0,37.20,29.7,3.9,6.20,251.0,0.270,4.04,0.0,76.10,42.50,85.0,17.0,29.8650,29.5870,18.4,26.5,78.50
7,64.10,53.0,43.80,29.8,3.2,5.10,260.0,0.810,6.36,0.0,80.30,47.60,88.0,21.0,29.9240,29.6670,16.1,24.2,79.10
8,61.75,51.0,40.35,29.8,3.0,4.85,273.0,0.400,8.34,0.0,78.10,45.30,85.0,21.0,29.9495,29.6945,16.1,24.2,78.90
9,56.80,47.0,32.90,29.9,3.3,5.40,263.0,0.160,9.17,0.0,73.70,38.90,83.0,18.0,30.0290,29.7000,16.1,24.2,77.00
10,45.70,48.0,24.00,29.9,4.6,7.30,255.0,0.430,10.71,0.0,59.60,32.50,82.0,23.0,30.0860,29.7530,17.3,26.5,59.60
11,38.20,40.0,13.90,30.0,7.4,11.40,250.0,0.140,11.55,0.0,50.40,25.10,75.0,20.0,30.2010,29.7990,21.9,32.2,50.40
12,30.85,44.0,8.50,30.0,7.2,10.90,243.0,0.100,12.67,0.0,39.95,19.15,73.0,26.0,30.2035,29.8170,23.0,33.4,39.95

In [14]:
print(df_month_group_med['Maximum gust speed (mph)'])

month_index
1     32.2
2     34.5
3     31.1
4     27.6
5     26.0
6     26.5
7     24.2
8     24.2
9     24.2
10    26.5
11    32.2
12    33.4
Name: Maximum gust speed (mph), dtype: float64

In [15]:
max_gust_value = (df_month_group_med['Maximum gust speed (mph)']).max()
max_gust_value

34.5

In [16]:
max_gust_month = (df_month_group_med['Maximum gust speed (mph)']).idxmax()
max_gust_month

2

### Determine the average temperature between the months of March 2010 to May 2012 (including both the months)

In [17]:
temp=df[(df['Date'] >= '2010-03-01') & (df['Date'] <= '2012-05-31')]
temp

,Day,Average temperature (°F),Average humidity (%),Average dewpoint (°F),Average barometer (in),Average windspeed (mph),Average gustspeed (mph),Average direction (°deg),Rainfall for month (in),Rainfall for year (in),...,Minimum temperature (°F),Maximum humidity (%),Minimum humidity (%),Maximum pressure,Minimum pressure,Maximum windspeed (mph),Maximum gust speed (mph),Maximum heat index (°F),Date,month_index
390,1/03/2010,26.1,74,18.4,30.2,2.2,3.4,53,0.02,0.59,...,14.3,90,40,30.375,30.086,15.0,22.0,39.1,2010-03-01,3
391,2/03/2010,27.8,58,12.9,30.2,1.4,2.4,91,0.02,0.59,...,10.5,86,21,30.387,30.012,10.4,14.0,48.8,2010-03-02,3
392,3/03/2010,31.4,56,15.5,30.0,4.5,6.4,315,0.02,0.59,...,15.4,84,23,30.180,29.942,18.4,26.0,48.3,2010-03-03,3
393,4/03/2010,29.9,63,17.9,30.0,1.6,2.9,191,0.02,0.59,...,16.4,83,32,30.138,29.787,6.9,255.0,44.6,2010-03-04,3
394,5/03/2010,29.9,59,16.3,29.9,10.1,14.2,316,0.02,0.59,...,20.0,85,34,29.949,29.693,24.2,36.0,36.9,2010-03-05,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1060,27/05/2012,49.4,19,8.1,29.6,11.7,17.3,241,1.22,2.14,...,42.5,37,10,29.801,29.296,28.8,38.0,58.3,2012-05-27,5
1061,28/05/2012,52.8,23,14.6,29.8,12.6,18.4,245,1.22,2.14,...,43.1,37,10,29.908,29.641,29.9,43.7,71.0,2012-05-28,5
1062,29/05/2012,51.0,35,21.7,29.9,2.3,4.1,318,1.22,2.14,...,30.1,60,12,30.028,29.755,13.8,24.2,75.6,2012-05-29,5
1063,30/05/2012,55.2,39,26.3,29.8,4.4,7.1,286,1.22,2.14,...,34.1,69,13,29.884,29.669,18.4,26.5,76.8,2012-05-30,5
1064,31/05/2012,51.3,55,34.6,29.9,3.0,4.9,59,1.22,2.14,...,34.9,83,33,29.946,29.807,13.8,19.6,64.2,2012-05-31,5

In [18]:
avg_temp = np.mean(temp['Average temperature (°F)'])
avg_temp

45.3322962962963

### Find the range of averange temperature  on Dec 2010

In [19]:
dec=df[(df['Date']>='2010-12-01') & (df['Date']<='2010-12-31')].iloc[:,1]
dec

662    42.2
663    44.8
664    31.3
665    28.8
666    34.3
667    34.3
668    40.4
669    39.6
670    35.9
671    25.2
672    34.8
673    45.8
674    46.3
675    34.1
676    20.2
677    15.7
678    29.7
679    36.5
680    33.9
681    25.0
682    25.1
683    32.9
684    24.4
685    24.1
686    35.4
687    31.4
688    31.7
689    35.5
690    17.5
691     1.5
Name: Average temperature (°F), dtype: float64

In [20]:
np.min(dec)

1.5

In [21]:
np.min(dec)

1.5

In [22]:
temp_range = (np.max(dec) - np.min(dec) )
temp_range

44.8

### Out of all available records which day has the highest difference between maximum_pressure and minimum_pressure
    - assign the date in string format as 'yyyy-mm-dd'. Make sure you enclose it with single quote

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3280 entries, 0 to 3279
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Day                       3280 non-null   object
 1   Average temperature (°F)  3280 non-null   float64
 2   Average humidity (%)      3280 non-null   int64
 3   Average dewpoint (°F)     3280 non-null   float64
 4   Average barometer (in)    3280 non-null   float64
 5   Average windspeed (mph)   3280 non-null   float64
 6   Average gustspeed (mph)   3280 non-null   float64
 7   Average direction (°deg)  3280 non-null   int64
 8   Rainfall for month (in)   3280 non-null   float64
 9   Rainfall for year (in)    3280 non-null   float64
 10  Maximum rain per minute   3280 non-null   float64
 11  Maximum temperature (°F)  3280 non-null   float64
 12  Minimum temperature (°F)  3280 non-null   float64
 13  Maximum humidity (%)      3280 non-null   int64
 14  Minimum humidity (%)      3280 non-null   int64
 15  Maximum pressure          3280 non-null   float64
 16  Minimum pressure          3280 non-null   float64
 17  Maximum windspeed (mph)   3280 non-null   float64
 18  Maximum gust speed (mph)  3280 non-null   float64
 19  Maximum heat index (°F)   3280 non-null   float64
 20  Date                      3280 non-null   datetime64[ns]
 21  month_index               3280 non-null   int64
dtypes: datetime64[ns](1), float64(15), int64(5), object(1)
memory usage: 563.9+ KB

In [24]:
df['pressurediff'] = df['Maximum pressure '] - df['Minimum pressure ']
df.head()

,Day,Average temperature (°F),Average humidity (%),Average dewpoint (°F),Average barometer (in),Average windspeed (mph),Average gustspeed (mph),Average direction (°deg),Rainfall for month (in),Rainfall for year (in),...,Maximum humidity (%),Minimum humidity (%),Maximum pressure,Minimum pressure,Maximum windspeed (mph),Maximum gust speed (mph),Maximum heat index (°F),Date,month_index,pressurediff
0,1/01/2009,37.8,35,12.7,29.7,26.4,36.8,274,0.0,0.0,...,44,27,29.762,29.596,41.4,59.0,40.1,2009-01-01,1,0.166
1,2/01/2009,43.2,32,14.7,29.5,12.8,18.0,240,0.0,0.0,...,43,16,29.669,29.268,35.7,51.0,52.8,2009-01-02,1,0.401
2,3/01/2009,25.7,60,12.7,29.7,8.3,12.2,290,0.0,0.0,...,89,35,30.232,29.260,25.3,38.0,41.2,2009-01-03,1,0.972
3,4/01/2009,9.3,67,0.1,30.4,2.9,4.5,47,0.0,0.0,...,79,35,30.566,30.227,12.7,20.0,32.0,2009-01-04,1,0.339
4,5/01/2009,23.5,30,-5.3,29.9,16.7,23.1,265,0.0,0.0,...,56,13,30.233,29.568,38.0,53.0,32.0,2009-01-05,1,0.665

In [25]:
maxpresdiff = df['pressurediff'].max()
maxpresdiff

16.602

In [26]:
np.argmax(df['pressurediff'])

3067

In [27]:
# maxpresdiff = df['pressurediff'].max()
# q9 = df[df['pressurediff'] == maxpresdiff].Date
# q9

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3280 entries, 0 to 3279
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Day                       3280 non-null   object
 1   Average temperature (°F)  3280 non-null   float64
 2   Average humidity (%)      3280 non-null   int64
 3   Average dewpoint (°F)     3280 non-null   float64
 4   Average barometer (in)    3280 non-null   float64
 5   Average windspeed (mph)   3280 non-null   float64
 6   Average gustspeed (mph)   3280 non-null   float64
 7   Average direction (°deg)  3280 non-null   int64
 8   Rainfall for month (in)   3280 non-null   float64
 9   Rainfall for year (in)    3280 non-null   float64
 10  Maximum rain per minute   3280 non-null   float64
 11  Maximum temperature (°F)  3280 non-null   float64
 12  Minimum temperature (°F)  3280 non-null   float64
 13  Maximum humidity (%)      3280 non-null   int64
 14  Minimum humidity (%)      3280 non-null   int64
 15  Maximum pressure          3280 non-null   float64
 16  Minimum pressure          3280 non-null   float64
 17  Maximum windspeed (mph)   3280 non-null   float64
 18  Maximum gust speed (mph)  3280 non-null   float64
 19  Maximum heat index (°F)   3280 non-null   float64
 20  Date                      3280 non-null   datetime64[ns]
 21  month_index               3280 non-null   int64
 22  pressurediff              3280 non-null   float64
dtypes: datetime64[ns](1), float64(16), int64(5), object(1)
memory usage: 589.5+ KB

In [29]:
df['Date'].value_counts()

2009-01-01    1
2015-09-07    1
2015-08-28    1
2015-08-29    1
2015-08-30    1
             ..
2012-07-01    1
2012-07-02    1
2012-07-03    1
2012-07-04    1
2018-10-28    1
Name: Date, Length: 3280, dtype: int64

In [30]:
# df['Date']=df['Date'].str.split('00:00:00').str[0]

In [31]:
# df['Date'].value_counts()

In [32]:
df['Date']=df['Date'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3280 entries, 0 to 3279
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Day                       3280 non-null   object
 1   Average temperature (°F)  3280 non-null   float64
 2   Average humidity (%)      3280 non-null   int64
 3   Average dewpoint (°F)     3280 non-null   float64
 4   Average barometer (in)    3280 non-null   float64
 5   Average windspeed (mph)   3280 non-null   float64
 6   Average gustspeed (mph)   3280 non-null   float64
 7   Average direction (°deg)  3280 non-null   int64
 8   Rainfall for month (in)   3280 non-null   float64
 9   Rainfall for year (in)    3280 non-null   float64
 10  Maximum rain per minute   3280 non-null   float64
 11  Maximum temperature (°F)  3280 non-null   float64
 12  Minimum temperature (°F)  3280 non-null   float64
 13  Maximum humidity (%)      3280 non-null   int64
 14  Minimum humidity (%)      3280 non-null   int64
 15  Maximum pressure          3280 non-null   float64
 16  Minimum pressure          3280 non-null   float64
 17  Maximum windspeed (mph)   3280 non-null   float64
 18  Maximum gust speed (mph)  3280 non-null   float64
 19  Maximum heat index (°F)   3280 non-null   float64
 20  Date                      3280 non-null   object
 21  month_index               3280 non-null   int64
 22  pressurediff              3280 non-null   float64
dtypes: float64(16), int64(5), object(2)
memory usage: 589.5+ KB

In [33]:
max_p_range_day = df.iloc[3067,20]
max_p_range_day

'2018-03-23'

### How many days falls under median (i.e equal to median value) of barrometer reading.

In [34]:
# med= df.iloc[:,4].median()
# med

In [35]:
med=df[(df['Average barometer (in)']==29.9)]

In [36]:
median_b_days = len(med)
median_b_days

534

### Out of all the available records how many days are within one standard deviation of average temperaturem

In [37]:
# std= round(df.iloc[:,1].std(),2)
# mean = round(df.iloc[:,1].mean(),2)
# q11 = df[(df.iloc[:,1] >= mean-std) & (df.iloc[:,1] <= mean + std)]
# q11 = len(q11)
# q11

In [38]:
# std= round(df.iloc[:,1].std(),2)
# std

In [39]:
stdd=np.std(df['Average temperature (°F)'])
stdd=round(stdd,2)
stdd

15.19

In [40]:
mn=np.mean(df['Average temperature (°F)'])
mn=round(mn,2)
mn

45.16

In [41]:
osd=df[(df['Average temperature (°F)']>=mn -stdd) & (df['Average temperature (°F)']<=mn + stdd)]

In [42]:
num_days_std = len(osd)
num_days_std

2092

## Once you are done with your solution make sure you have saved the notebook (ctrl + s)